_target_: src.logger.CometMLWriter
# Override project_name and run_name in your top-level config (e.g. baseline_vqa.yaml).
project_name: "vqa_gnn"
workspace: null
run_name: "vqa_gnn_run"
mode: "online"
loss_names: ["loss"] # which losses to log (useful for multi-loss tasks, s.a. GANs)
log_checkpoints: False # set to True if you want to log save_dir with checkpoints to CometML
id_length: 32 # length of the run_id
